Repository MapJiri/mapjiri-server, pull requests merged in 2025-02, with the labels that each got.

#4 Feat/#2/restaurant 근처 음식점 조회 기능
  src/main/java/project/mapjiri/domain/place/controller/LocationController.java
  src/main/java/project/mapjiri/domain/place/dto/AddressResponseDto.java
  src/main/java/project/mapjiri/domain/restaurant/controller/SearchController.java
  src/main/java/project/mapjiri/domain/restaurant/dto/NearbyRestaurantsResponseDto.java
  src/main/java/project/mapjiri/global/client/KakaoMapClient.java
  src/main/java/project/mapjiri/global/client/dto/KakaoAddressResponseDto.java
  src/main/java/project/mapjiri/global/client/dto/KakaoNearbyRestaurantResponseDto.java
  src/main/java/project/mapjiri/global/config/RestClientConfig.java
  src/main/java/project/mapjiri/global/exception/MyErrorCode.java
  src/main/java/project/mapjiri/global/exception/MyExceptionHandler.java
  src/test/java/project/mapjiri/global/client/KakaoMapClientTest.java
Labels: enhancement

#6 근처 식당 정보에 전화번호 추가
  src/main/java/project/mapjiri/domain/restaurant/dto/NearbyRestaurantsResponseDto.java
  src/main/java/project/mapjiri/global/client/dto/KakaoNearbyRestaurantResponseDto.java
  src/test/java/project/mapjiri/global/client/KakaoMapClientTest.java
Labels: enhancement

#3 Feat/#1/review get
  src/main/java/project/mapjiri/domain/restaurant/model/Restaurant.java
  src/main/java/project/mapjiri/domain/restaurant/model/RestaurantRepository.java
  src/main/java/project/mapjiri/domain/restaurant/model/ReviewTag.java
  src/main/java/project/mapjiri/domain/review/controller/ReviewController.java
  src/main/java/project/mapjiri/domain/review/dto/ReviewListResponse.java
  src/main/java/project/mapjiri/domain/review/dto/ReviewResponse.java
  src/main/java/project/mapjiri/domain/review/model/Review.java
  src/main/java/project/mapjiri/domain/review/model/ReviewSort.java
  src/main/java/project/mapjiri/domain/review/model/ReviewTag.java
  src/main/java/project/mapjiri/domain/review/repository/ReviewRepository.java
  src/main/java/project/mapjiri/domain/review/service/ReviewService.java
  src/main/java/project/mapjiri/domain/review/service/ReviewServiceImpl.java
  src/test/java/project/mapjiri/domain/review/model/ReviewTagTest.java
  src/test/java/project/mapjiri/domain/review/service/ReviewServiceImplTest.java
Labels: feat

#8 feat: user 생성자 추가
  src/main/java/project/mapjiri/domain/user/model/User.java
Labels: feat

#11 [Feat] Spring Security, Jwt 인증 초기 구현
  build.gradle
  src/main/java/project/mapjiri/domain/user/filter/JwtAuthenticationFilter.java
  src/main/java/project/mapjiri/domain/user/model/Role.java
  src/main/java/project/mapjiri/domain/user/model/User.java
  src/main/java/project/mapjiri/domain/user/provider/JwtTokenProvider.java
  src/main/java/project/mapjiri/domain/user/repository/UserRepository.java
  src/main/java/project/mapjiri/global/config/WebSecurityConfig.java
Labels: feat

#16 [Feat] User Controller, Serivce 구현
  src/main/java/project/mapjiri/domain/user/controller/UserController.java
  src/main/java/project/mapjiri/domain/user/dto/request/SignInRequestDto.java
  src/main/java/project/mapjiri/domain/user/dto/request/SignUpRequestDto.java
  src/main/java/project/mapjiri/domain/user/dto/response/SignInResponseDto.java
  src/main/java/project/mapjiri/domain/user/dto/response/SignUpResponseDto.java
  src/main/java/project/mapjiri/domain/user/repository/UserRepository.java
  src/main/java/project/mapjiri/domain/user/service/UserService.java
Labels: feat

#20 [Refactor] 변경된 테이블 구조 기준으로 엔티티 연관관계 수정
  src/main/java/project/mapjiri/domain/menu/model/Menu.java
  src/main/java/project/mapjiri/domain/menustar/model/MenuStar.java
  src/main/java/project/mapjiri/domain/place/model/Place.java
  src/main/java/project/mapjiri/domain/placeStar/model/PlaceStar.java
  src/main/java/project/mapjiri/domain/restaurant/model/Restaurant.java
Labels: refactor

#13 [Feat] 즐겨찾기 기능 구현
  src/main/java/project/mapjiri/domain/menustar/controller/MenuStarController.java
  src/main/java/project/mapjiri/domain/menustar/dto/MenuStarRequest.java
  src/main/java/project/mapjiri/domain/menustar/model/MenuStar.java
  src/main/java/project/mapjiri/domain/menustar/repository/MenuStarRepository.java
  src/main/java/project/mapjiri/domain/menustar/service/MenuStarService.java
  src/main/java/project/mapjiri/domain/placeStar/controller/PlaceStarController.java
  src/main/java/project/mapjiri/domain/placeStar/dto/PlaceStarRequest.java
  src/main/java/project/mapjiri/domain/placeStar/model/PlaceStar.java
  src/main/java/project/mapjiri/domain/placeStar/repository/PlaceStarRepository.java
  src/main/java/project/mapjiri/domain/placeStar/service/PlaceStarService.java
Labels: feat, chore

#22 [Feat] User Domain Redis 기능 구현
  build.gradle
  src/main/java/project/mapjiri/domain/user/controller/UserController.java
  src/main/java/project/mapjiri/domain/user/dto/request/LogoutRequestDto.java
  src/main/java/project/mapjiri/domain/user/dto/request/RefreshAccessTokenRequestDto.java
  src/main/java/project/mapjiri/domain/user/dto/response/RefreshAccessTokenResponseDto.java
  src/main/java/project/mapjiri/domain/user/provider/JwtTokenProvider.java
  src/main/java/project/mapjiri/domain/user/service/RedisService.java
  src/main/java/project/mapjiri/domain/user/service/UserService.java
  src/main/java/project/mapjiri/global/config/RedisConfig.java
Labels: feat

#21 [Feat] Place, Menu CRUD 구현, CSV 파일 DB 저장 구현
  build.gradle
  src/main/java/project/mapjiri/domain/menu/controller/MenuController.java
  src/main/java/project/mapjiri/domain/menu/model/Menu.java
  src/main/java/project/mapjiri/domain/menu/repository/MenuRepository.java
  src/main/java/project/mapjiri/domain/menu/service/MenuService.java
  src/main/java/project/mapjiri/domain/place/controller/LocationController.java
  src/main/java/project/mapjiri/domain/place/model/Place.java
  src/main/java/project/mapjiri/domain/place/repository/PlaceRepository.java
  src/main/java/project/mapjiri/domain/place/service/PlaceService.java
  src/main/java/project/mapjiri/domain/utils/runner/CsvLoaderRunner.java
  src/main/java/project/mapjiri/domain/utils/service/CsvLoaderService.java
  src/main/java/project/mapjiri/global/exception/MyErrorCode.java
Labels: feat

#28 [Feat] getUserIdfromToken 생성
  src/main/java/project/mapjiri/domain/user/service/UserService.java
Labels: feat

#30 [Fix] createAccessToken userId 필드 삭제
  src/main/java/project/mapjiri/domain/user/service/UserService.java
Labels: fix

#23 [Feat]실시간 음식점 검색 키워드 랭킹 기능 구현
  src/main/java/project/mapjiri/domain/restaurant/controller/SearchController.java
  src/main/java/project/mapjiri/domain/restaurant/dto/SearchRankingResponseDto.java
  src/main/java/project/mapjiri/domain/restaurant/service/SearchService.java
  src/main/java/project/mapjiri/global/config/RedisConfig.java
  src/test/java/project/mapjiri/domain/restaurant/service/SearchServiceTest.java
Labels: feat

#32 [Feat] 이메일 인증 기능 구현
  build.gradle
  src/main/java/project/mapjiri/domain/user/controller/UserController.java
  src/main/java/project/mapjiri/domain/user/dto/request/MailSendRequestDto.java
  src/main/java/project/mapjiri/domain/user/dto/request/MailVerifyRequestDto.java
  src/main/java/project/mapjiri/domain/user/service/MailService.java
  src/main/java/project/mapjiri/domain/user/service/RedisService.java
  src/main/java/project/mapjiri/domain/user/service/UserService.java
  src/main/resources/application.yml
Labels: feat

#29 [Chore] 도커를 이용한 수동 빌드 구성
  Dockerfile
  build.sh
  src/test/java/project/mapjiri/MapjiriApplicationTests.java
  src/test/java/project/mapjiri/domain/review/service/ReviewServiceImplTest.java
Labels: refactor, chore

#31 [Chore] OAS 및 Jacoco 빌드 설정
  .gitignore
  build.gradle
  src/main/java/project/mapjiri/domain/utils/service/CsvLoaderService.java
  src/main/java/project/mapjiri/global/config/StaticRoutingConfiguration.java
  src/main/java/project/mapjiri/global/config/WebSecurityConfig.java
  src/main/resources/static/swagger-ui/images/favicon-16x16.png
  src/main/resources/static/swagger-ui/images/favicon-32x32.png
  src/main/resources/static/swagger-ui/js/swagger-ui-bundle.js
  src/main/resources/static/swagger-ui/js/swagger-ui-bundle.js.map
  src/main/resources/static/swagger-ui/js/swagger-ui-standalone-preset.js
  src/main/resources/static/swagger-ui/js/swagger-ui-standalone-preset.js.map
  src/main/resources/static/swagger-ui/style/swagger-ui.css
  src/main/resources/static/swagger-ui/style/swagger-ui.css.map
  src/main/resources/static/swagger-ui/swagger-ui.html
Labels: feat

#36 [Refactor] 일관성있는 class 이름으로 수정
  src/main/java/project/mapjiri/global/config/StaticRoutingConfig.java
Labels: refactor

#39 [Fix] User signIn 패스워드 비교 로직 수정
  src/main/java/project/mapjiri/domain/user/service/UserService.java
Labels: fix

#43 feat: User Domain 테스트 코드 작성
  src/test/java/project/mapjiri/domain/user/service/UserServiceTest.java
Labels: feat

#45 [Feat] 가게명, 태그, 후기 목록 등 가게 상세 정보 등록 API 구현
  src/main/java/project/mapjiri/domain/restaurant/controller/RestaurantController.java
  src/main/java/project/mapjiri/domain/restaurant/dto/RestaurantCreateRequestDto.java
  src/main/java/project/mapjiri/domain/restaurant/dto/RestaurantListCreateRequestDto.java
  src/main/java/project/mapjiri/domain/restaurant/model/Restaurant.java
  src/main/java/project/mapjiri/domain/restaurant/model/Tag.java
  src/main/java/project/mapjiri/domain/restaurant/service/RestaurantCreateResponseDto.java
  src/main/java/project/mapjiri/domain/restaurant/service/RestaurantListCreateResponseDto.java
  src/main/java/project/mapjiri/domain/restaurant/service/RestaurantService.java
  src/main/java/project/mapjiri/domain/restaurant/service/RestaurantServiceImpl.java
  src/main/java/project/mapjiri/domain/review/controller/ReviewController.java
  src/main/java/project/mapjiri/domain/review/dto/ReviewCreateResponseDto.java
  src/main/java/project/mapjiri/domain/review/model/Review.java
  src/main/java/project/mapjiri/domain/review/repository/ReviewRepository.java
  src/main/java/project/mapjiri/domain/review/service/ReviewServiceImpl.java
  src/main/java/project/mapjiri/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/static/.DS_Store
  src/test/java/project/mapjiri/domain/restaurant/service/RestaurantServiceImplTest.java
  src/test/java/project/mapjiri/domain/review/service/ReviewServiceImplTest.java
Labels: feat

#35 [feat, fix] 즐겨찾기 활성화 , API 추가
  src/main/java/project/mapjiri/domain/menu/controller/MenuController.java
  src/main/java/project/mapjiri/domain/menu/model/Menu.java
  src/main/java/project/mapjiri/domain/menu/repository/MenuRepository.java
  src/main/java/project/mapjiri/domain/menu/service/MenuService.java
  src/main/java/project/mapjiri/domain/menustar/controller/MenuStarController.java
  src/main/java/project/mapjiri/domain/menustar/dto/MenuStarRequest.java
  src/main/java/project/mapjiri/domain/menustar/dto/request/AddMenuStarRequest.java
  src/main/java/project/mapjiri/domain/menustar/service/MenuStarService.java
  src/main/java/project/mapjiri/domain/place/controller/LocationController.java
  src/main/java/project/mapjiri/domain/place/repository/PlaceRepository.java
  src/main/java/project/mapjiri/domain/place/service/PlaceService.java
  src/main/java/project/mapjiri/domain/placeStar/controller/PlaceStarController.java
  src/main/java/project/mapjiri/domain/placeStar/dto/request/AddPlaceStarRequest.java
  src/main/java/project/mapjiri/domain/placeStar/service/PlaceStarService.java
  src/main/java/project/mapjiri/domain/user/filter/JwtAuthenticationFilter.java
  src/main/java/project/mapjiri/domain/user/service/UserService.java
  src/main/java/project/mapjiri/global/config/MvcConfig.java
  src/main/java/project/mapjiri/global/config/WebSecurityConfig.java
  src/main/java/project/mapjiri/global/exception/MyErrorCode.java
  src/test/java/project/mapjiri/domain/menu/service/MenuServiceTest.java
  src/test/java/project/mapjiri/domain/menustar/service/MenuStarServiceTest.java
  src/test/java/project/mapjiri/domain/place/service/PlaceServiceTest.java
  src/test/java/project/mapjiri/domain/placeStar/service/PlaceStarServiceTest.java
Labels: fix, feat

#50 Feat/#46/restaurant register fix
  src/main/java/project/mapjiri/domain/restaurant/controller/RestaurantController.java
  src/main/java/project/mapjiri/domain/restaurant/dto/RestaurantCreateResponseDto.java
  src/main/java/project/mapjiri/domain/restaurant/dto/RestaurantListCreateResponseDto.java
  src/main/java/project/mapjiri/domain/restaurant/model/RestaurantRepository.java
  src/main/java/project/mapjiri/domain/restaurant/service/RestaurantService.java
  src/main/java/project/mapjiri/domain/restaurant/service/RestaurantServiceImpl.java
  src/main/java/project/mapjiri/domain/review/controller/ReviewController.java
  src/main/java/project/mapjiri/domain/review/model/Review.java
  src/main/java/project/mapjiri/domain/review/service/ReviewService.java
  src/main/java/project/mapjiri/domain/review/service/ReviewServiceImpl.java
  src/main/java/project/mapjiri/global/exception/MyErrorCode.java
  src/test/java/project/mapjiri/domain/restaurant/service/RestaurantServiceImplTest.java
  src/test/java/project/mapjiri/domain/review/service/ReviewServiceImplTest.java
Labels: fix, refactor

#48 [Fix] User 테스트 코드 수정
  src/test/java/project/mapjiri/domain/user/service/UserServiceTest.java
Labels: fix

#52 [Feat] RestDocs + swagger 세팅 및 구현
  build.gradle
  src/main/java/project/mapjiri/domain/user/dto/request/RefreshAccessTokenRequestDto.java
  src/main/java/project/mapjiri/global/client/dto/KakaoAddressResponseDto.java
  src/main/java/project/mapjiri/global/client/dto/KakaoNearbyRestaurantResponseDto.java
  src/test/java/project/mapjiri/domain/menu/controller/MenuControllerTest.java
  src/test/java/project/mapjiri/domain/menustar/controller/MenuStarControllerTest.java
  src/test/java/project/mapjiri/domain/place/controller/LocationControllerTest.java
  src/test/java/project/mapjiri/domain/placeStar/controller/PlaceStarControllerTest.java
  src/test/java/project/mapjiri/domain/restaurant/controller/RestaurantControllerTest.java
  src/test/java/project/mapjiri/domain/restaurant/controller/SearchControllerTest.java
  src/test/java/project/mapjiri/domain/review/controller/ReviewControllerTest.java
  src/test/java/project/mapjiri/domain/user/controller/UserControllerTest.java
  src/test/java/project/mapjiri/support/annotation/WithMockCustom.java
  src/test/java/project/mapjiri/support/config/RestDocsConfig.java
  src/test/java/project/mapjiri/support/fixture/UserFixture.java
  src/test/java/project/mapjiri/support/security/MockCustomUserSecurityContextFactory.java
  src/test/java/project/module/RestDocsSupport.java
Labels: feat
